// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ2vXwRQYt-BqAlFL1wDNQ5ycEjXsWScQ',
    appId: '1:1050936980158:web:db2f1b968b527be99b24ef',
    messagingSenderId: '1050936980158',
    projectId: 'neuroease-9d4e4',
    authDomain: 'neuroease-9d4e4.firebaseapp.com',
    storageBucket: 'neuroease-9d4e4.firebasestorage.app',
    measurementId: 'G-SCN648TR4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4VHjO5H6dbS74YqTM127KrR9dCMfIzo',
    appId: '1:1050936980158:android:0f301380b56994729b24ef',
    messagingSenderId: '1050936980158',
    projectId: 'neuroease-9d4e4',
    storageBucket: 'neuroease-9d4e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-NTv1mNVWQgNRW9_WRTL_pzA9ViTYeo',
    appId: '1:1050936980158:ios:164f725a9fabe1189b24ef',
    messagingSenderId: '1050936980158',
    projectId: 'neuroease-9d4e4',
    storageBucket: 'neuroease-9d4e4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4-NTv1mNVWQgNRW9_WRTL_pzA9ViTYeo',
    appId: '1:1050936980158:ios:164f725a9fabe1189b24ef',
    messagingSenderId: '1050936980158',
    projectId: 'neuroease-9d4e4',
    storageBucket: 'neuroease-9d4e4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ2vXwRQYt-BqAlFL1wDNQ5ycEjXsWScQ',
    appId: '1:1050936980158:web:928fbc8c60ef23ab9b24ef',
    messagingSenderId: '1050936980158',
    projectId: 'neuroease-9d4e4',
    authDomain: 'neuroease-9d4e4.firebaseapp.com',
    storageBucket: 'neuroease-9d4e4.firebasestorage.app',
    measurementId: 'G-TWSMXYQ3Q2',
  );
}
